name: intro_ai
channels:
  - rdkit
  - pytorch
  - defaults
dependencies:
  - python=3.7.11
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - notebook=6.4.3
  - numpy=1.20.3
  - pandas=1.3.2
  - pip=21.0.1
  - pytorch=1.9.0
  - rdkit=2020.09.1.0
  - scipy=1.7.1
  - seaborn=0.11.2
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - pip:
    - scikit-learn==0.24.2
    - sklearn==0.0
    - tqdm==4.62.2

